### ISSUE TITLE
"action wants to remove README.md but it does not exist"

### ISSUE THREAD

**Issue by hamilton** [graph-paper-org/app-template#14]
Ran degit on the template and got this:

```

npx degit graph-paper-org/app-template test
> cloned graph-paper-org/app-template#master to test
! action wants to remove README.md but it does not exist
> removed: 

```

Not sure I understand the warning since `README.md` exists.

**Comment by openjck** [comment]
That's interesting. I'm not getting that, but I'll keep digging.

**Comment by openjck** [comment]
It looks like *npx* will use a binary on the `PATH` if one exists. I'm wondering if you might have an old version of *degit* installed locally.

Would you mind trying this?

`npx ---ignore-existing degit@latest graph-paper-org/app-template test`

If that works, try running `npm update -g graph-paper` to update the global package or `npm rm -g graph-paper` to remove the global package.

**Comment by openjck** [comment]
It looks like *npx* will use a binary on the `PATH` if one exists. I'm wondering if you might have an old version of *degit* installed on your machine.

Would you mind trying this?

`npx --ignore-existing degit@latest graph-paper-org/app-template test`

If that works, try running `npm update -g degit` to update the global package or `npm rm -g degit` to remove the global package.

**Comment by hamilton** [comment]
Yep, that fixed it. I'll update.
